# Generated by Django 2.0.1 on 2018-02-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenieSpider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('xpath', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ItemStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xpath', models.TextField()),
                ('details_url', models.TextField(blank=True, help_text='Xpath for item details url', null=True)),
                ('attributes', models.ManyToManyField(to='maincrawler.ItemAttribute')),
            ],
        ),
        migrations.AddField(
            model_name='geniespider',
            name='items_structure',
            field=models.ManyToManyField(to='maincrawler.ItemStructure'),
        ),
    ]
