# Generated by Django 2.0.1 on 2018-03-26 06:47

from django.db import migrations, models
import maincrawler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maincrawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xpath', models.TextField(blank=True, null=True)),
                ('details_url', models.TextField(blank=True, help_text='Xpath for item details url', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenieSpider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('items_structure', models.IntegerField(verbose_name=maincrawler.models.Extractor)),
            ],
        ),
        migrations.CreateModel(
            name='ItemAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('xpath', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='extractor',
            name='attributes',
            field=models.ManyToManyField(to='maincrawler.ItemAttribute'),
        ),
    ]
