# Generated by Django 2.0.1 on 2018-03-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maincrawler', '0002_auto_20180326_0647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geniespider',
            name='items_structure',
        ),
        migrations.AddField(
            model_name='geniespider',
            name='items_structure',
            field=models.ManyToManyField(to='maincrawler.Extractor'),
        ),
    ]
