# Generated by Django 2.0.1 on 2018-03-26 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maincrawler', '0003_auto_20180326_0648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geniespider',
            name='items_structure',
        ),
        migrations.AddField(
            model_name='geniespider',
            name='items_structure',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='spider', to='maincrawler.Extractor'),
            preserve_default=False,
        ),
    ]
