# Generated by Django 2.0.1 on 2018-03-26 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maincrawler', '0005_auto_20180326_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extractor',
            name='spider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extractors', to='maincrawler.GenieSpider'),
        ),
    ]
