# Generated by Django 2.0.1 on 2018-01-29 09:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maincrawler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpiderTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logs', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('extracted_items', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=[], null=True)),
                ('scrapyd_task_id', models.TextField(blank=True, null=True)),
                ('spider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maincrawler.GenoSpider')),
            ],
        ),
    ]
