# Generated by Django 2.0.1 on 2018-04-01 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmanager', '0002_spidertask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('sql', 'SQL'), ('xml', 'XML')], max_length=5)),
                ('file', models.FileField(upload_to='exports')),
            ],
        ),
        migrations.AlterField(
            model_name='spidertask',
            name='status',
            field=models.CharField(blank=True, choices=[('started', 'Task is running'), ('initiated', 'Task is initiated'), ('finished', 'Task is finished'), ('error', 'Task is raised an error'), ('canceled', 'Task is canceled'), ('pending', 'Task is pending'), ('running', 'Task is running')], default='initiated', editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exportfile',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasksmanager.SpiderTask'),
        ),
    ]
