# Generated by Django 2.0.1 on 2018-04-04 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasksmanager', '0003_auto_20180401_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportfile',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exported_file', to='tasksmanager.SpiderTask'),
        ),
    ]
